/**
 * PageSpec — the Runtime JSON contract for Valentino Engine.
 * Every UI component generated by Valentino must conform to this schema.
 */

export interface PageSpec {
  id: string;
  version: string;
  layout: LayoutSpec;
  components: ComponentSpec[];
  meta?: Record<string, string>;
}

export interface LayoutSpec {
  type: 'hero' | 'dashboard' | 'form' | 'list' | 'detail';
  responsive: boolean;
  theme: string;
}

export interface ComponentSpec {
  id: string;
  type: string;
  labelKey: string;
  props?: Record<string, unknown>;
  children?: ComponentSpec[];
  actions?: ActionSpec[];
}

export interface ActionSpec {
  type: 'navigate' | 'submit' | 'open-modal' | 'custom';
  labelKey: string;
  target?: string;
}

export function validatePageSpec(spec: unknown): spec is PageSpec {
  if (typeof spec !== 'object' || spec === null) return false;
  const s = spec as Record<string, unknown>;
  return typeof s.id === 'string' && typeof s.version === 'string' && Array.isArray(s.components);
}
