/**
 * Valentino Spool — analyze an existing site and generate Valentino-compatible CSS + theme-pack.
 *
 * The spool reads CSS files from a directory, extracts colors and layout patterns,
 * maps them to Valentino's token contract, and generates:
 *   1. custom-tokens.css — color overrides for tokens.css
 *   2. A recommendation for which template to use (corporate, landing, etc.)
 *
 * 80% automatic, 20% operator via cockpit.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { resolve, extname } from 'node:path';
import { parseColor, relativeLuminance, contrastRatio } from './contrast.js';

// --- Types ---

export interface ExtractedColor {
  value: string;
  rgb: [number, number, number];
  luminance: number;
  count: number;
  role: 'background' | 'text' | 'accent' | 'border' | 'unknown';
}

export interface SpoolAnalysis {
  sourceDir: string;
  cssFiles: string[];
  totalLines: number;
  colors: ExtractedColor[];
  darkestBg: ExtractedColor | null;
  lightestBg: ExtractedColor | null;
  primaryText: ExtractedColor | null;
  accents: ExtractedColor[];
  suggestedTemplate: 'corporate' | 'landing' | 'blog' | 'unknown';
  sectionCount: number;
  hasHero: boolean;
  hasGrid: boolean;
  hasForm: boolean;
}

export interface SpoolOutput {
  analysis: SpoolAnalysis;
  customTokensCss: string;
}

// --- Color extraction ---

const HEX_RE = /#(?:[0-9a-fA-F]{3,4}){1,2}\b/g;
const RGB_RE = /rgba?\(\s*\d+\s*,\s*\d+\s*,\s*\d+(?:\s*,\s*[\d.]+)?\s*\)/g;

function extractColorsFromCss(css: string): Map<string, { rgb: [number, number, number]; count: number }> {
  const map = new Map<string, { rgb: [number, number, number]; count: number }>();

  const addColor = (raw: string) => {
    const rgb = parseColor(raw);
    if (!rgb) return;
    const key = `#${rgb.map(c => c.toString(16).padStart(2, '0')).join('')}`;
    const existing = map.get(key);
    if (existing) {
      existing.count++;
    } else {
      map.set(key, { rgb, count: 1 });
    }
  };

  for (const match of css.matchAll(HEX_RE)) addColor(match[0]);
  for (const match of css.matchAll(RGB_RE)) addColor(match[0]);

  return map;
}

/** HSV saturation (0-1) from RGB. Low saturation = gray, not accent. */
function rgbSaturation(rgb: [number, number, number]): number {
  const [r, g, b] = rgb.map(c => c / 255);
  const max = Math.max(r, g, b);
  if (max === 0) return 0;
  const min = Math.min(r, g, b);
  return (max - min) / max;
}

const MIN_ACCENT_SATURATION = 0.15;

function inferColorRole(rgb: [number, number, number], lum: number): ExtractedColor['role'] {
  if (lum < 0.05) return 'background';  // very dark → likely bg
  if (lum > 0.85) return 'background';  // very light → likely bg
  if (lum < 0.15) return 'text';        // dark → likely text
  if (lum > 0.7) return 'text';         // light text on dark bg
  // mid-range: accent only if saturated enough, otherwise border/gray
  if (rgbSaturation(rgb) < MIN_ACCENT_SATURATION) return 'border';
  return 'accent';
}

// --- Pattern detection ---

function detectPatterns(css: string) {
  const lower = css.toLowerCase();
  return {
    hasHero: /\.hero|hero[-_]|data-rhythm-profile=['"]hero/i.test(css),
    hasGrid: /display:\s*grid|grid-template|\.grid|\.row|\.col-/i.test(css),
    hasForm: /form|input|textarea|\.contact|\.subscribe/i.test(css),
    hasPricing: /\.pricing|\.plan|\.tier/i.test(css),
    hasBlog: /\.post|\.article|\.blog|\.reading/i.test(css),
    hasTestimonial: /\.testimonial|\.quote|\.review/i.test(css),
    sectionCount: (lower.match(/section|\.section|data-surface/g) || []).length,
  };
}

function suggestTemplate(patterns: ReturnType<typeof detectPatterns>): SpoolAnalysis['suggestedTemplate'] {
  if (patterns.hasBlog) return 'blog';
  if (patterns.hasPricing || patterns.hasTestimonial) return 'corporate';
  if (patterns.hasHero && patterns.sectionCount <= 6) return 'landing';
  if (patterns.hasGrid || patterns.hasForm) return 'corporate';
  return 'unknown';
}

// --- CSS generation ---

function rgbToHex(rgb: [number, number, number]): string {
  return '#' + rgb.map(c => c.toString(16).padStart(2, '0')).join('');
}

function generateCustomTokens(analysis: SpoolAnalysis): string {
  const lines: string[] = [
    '/* === VALENTINO CUSTOM TOKENS (generated by spool) ===',
    ` * Source: ${analysis.sourceDir}`,
    ` * ${analysis.cssFiles.length} CSS files, ${analysis.totalLines} lines analyzed`,
    ` * Suggested template: ${analysis.suggestedTemplate}`,
    ' *',
    ' * Import AFTER tokens.css to override defaults:',
    ' *   @import \'@hale-bopp/valentino-engine/css/tokens.css\';',
    ' *   @import \'./custom-tokens.css\';',
    ' *   @import \'@hale-bopp/valentino-engine/css/framework.base.css\';',
    ' */',
    '',
    ':root {',
  ];

  if (analysis.darkestBg) {
    lines.push(`    /* Extracted darkest background */`);
    lines.push(`    --bg-deep-void: ${analysis.darkestBg.value};`);
  }

  if (analysis.primaryText) {
    lines.push(`    /* Extracted primary text color */`);
    const lum = analysis.primaryText.luminance;
    if (lum > 0.5) {
      lines.push(`    --text-primary: ${analysis.primaryText.value};`);
    }
  }

  if (analysis.accents.length >= 1) {
    lines.push('');
    lines.push('    /* Extracted accent colors (mapped to 3 slots) */');
    const sorted = [...analysis.accents].sort((a, b) => b.count - a.count);
    if (sorted[0]) lines.push(`    --accent-neural-cyan: ${sorted[0].value};`);
    if (sorted[1]) lines.push(`    --accent-violet: ${sorted[1].value};`);
    if (sorted[2]) lines.push(`    --text-sovereign-gold: ${sorted[2].value};`);
  }

  if (analysis.lightestBg) {
    lines.push('');
    lines.push('    /* Extracted lightest background (for light surfaces) */');
    lines.push(`    --valentino-surface-default-background: ${analysis.lightestBg.value};`);
  }

  lines.push('}');
  return lines.join('\n');
}

// --- Shared analysis pipeline ---

function analyzeCss(source: string, fileNames: string[], allCss: string, totalLines: number): SpoolOutput {
  const colorMap = extractColorsFromCss(allCss);
  const colors: ExtractedColor[] = [];
  for (const [value, { rgb, count }] of colorMap) {
    const lum = relativeLuminance(rgb[0], rgb[1], rgb[2]);
    colors.push({ value, rgb, luminance: lum, count, role: inferColorRole(rgb, lum) });
  }
  colors.sort((a, b) => b.count - a.count);

  const backgrounds = colors.filter(c => c.role === 'background');
  const texts = colors.filter(c => c.role === 'text');
  const accents = colors.filter(c => c.role === 'accent');

  const darkestBg = backgrounds.length > 0
    ? backgrounds.reduce((a, b) => a.luminance < b.luminance ? a : b)
    : null;
  const lightestBg = backgrounds.length > 0
    ? backgrounds.reduce((a, b) => a.luminance > b.luminance ? a : b)
    : null;
  const primaryText = texts.length > 0
    ? texts.reduce((a, b) => b.count > a.count ? b : a)
    : null;

  const patterns = detectPatterns(allCss);

  const analysis: SpoolAnalysis = {
    sourceDir: source,
    cssFiles: fileNames,
    totalLines,
    colors: colors.slice(0, 20),
    darkestBg,
    lightestBg,
    primaryText,
    accents: accents.slice(0, 5),
    suggestedTemplate: suggestTemplate(patterns),
    sectionCount: patterns.sectionCount,
    hasHero: patterns.hasHero,
    hasGrid: patterns.hasGrid,
    hasForm: patterns.hasForm,
  };

  return { analysis, customTokensCss: generateCustomTokens(analysis) };
}

// --- Main spool function (directory) ---

export function spool(dir: string): SpoolOutput {
  const absDir = resolve(dir);

  const cssFiles: string[] = [];
  const walkDir = (d: string) => {
    for (const entry of readdirSync(d)) {
      const full = resolve(d, entry);
      if (entry === 'node_modules' || entry === '.git' || entry === 'dist') continue;
      const stat = statSync(full);
      if (stat.isDirectory()) walkDir(full);
      else if (extname(entry) === '.css') cssFiles.push(full);
    }
  };
  walkDir(absDir);

  if (cssFiles.length === 0) {
    throw new Error(`No CSS files found in ${absDir}`);
  }

  let totalLines = 0;
  let allCss = '';
  for (const file of cssFiles) {
    const content = readFileSync(file, 'utf-8');
    totalLines += content.split('\n').length;
    allCss += content + '\n';
  }

  const fileNames = cssFiles.map(f => f.replace(absDir + '/', '').replace(absDir + '\\', ''));
  return analyzeCss(absDir, fileNames, allCss, totalLines);
}

// --- URL spool function ---

const LINK_CSS_RE = /<link[^>]+rel=["']stylesheet["'][^>]*href=["']([^"']+)["'][^>]*>/gi;
const LINK_CSS_RE2 = /<link[^>]+href=["']([^"']+)["'][^>]*rel=["']stylesheet["'][^>]*>/gi;
const STYLE_RE = /<style[^>]*>([\s\S]*?)<\/style>/gi;

function resolveUrl(base: string, href: string): string {
  try {
    return new URL(href, base).href;
  } catch {
    return href;
  }
}

export async function spoolFromUrl(url: string): Promise<SpoolOutput> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  const html = await res.text();

  // Extract inline <style> blocks
  const cssChunks: { name: string; css: string }[] = [];
  let styleIdx = 0;
  for (const match of html.matchAll(STYLE_RE)) {
    cssChunks.push({ name: `<style#${styleIdx++}>`, css: match[1] });
  }

  // Extract <link rel="stylesheet"> hrefs
  const cssUrls = new Set<string>();
  for (const re of [LINK_CSS_RE, LINK_CSS_RE2]) {
    for (const match of html.matchAll(re)) {
      cssUrls.add(resolveUrl(url, match[1]));
    }
  }

  // Fetch external stylesheets (parallel, best-effort)
  const fetches = [...cssUrls].map(async (cssUrl) => {
    try {
      const r = await fetch(cssUrl);
      if (!r.ok) return null;
      const css = await r.text();
      const name = new URL(cssUrl).pathname.split('/').pop() || cssUrl;
      return { name, css };
    } catch {
      return null;
    }
  });
  const results = await Promise.all(fetches);
  for (const r of results) {
    if (r) cssChunks.push(r);
  }

  if (cssChunks.length === 0) {
    throw new Error(`No CSS found at ${url} (no <style> blocks or <link rel="stylesheet"> tags)`);
  }

  let totalLines = 0;
  let allCss = '';
  for (const chunk of cssChunks) {
    totalLines += chunk.css.split('\n').length;
    allCss += chunk.css + '\n';
  }

  // Also analyze the HTML itself for pattern detection (sections, hero, grid, etc.)
  allCss += '\n' + html;

  return analyzeCss(url, cssChunks.map(c => c.name), allCss, totalLines);
}
